# Generated by Django 4.0.3 on 2022-04-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_genres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animegenremodel',
            name='type',
        ),
    ]
