# Generated by Django 4.0.3 on 2022-04-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_animegenremodel_alter_animeinfomodel_anime_genres'),
        ('anime_genres', '0002_remove_animegenremodel_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimeGenreModel',
        ),
    ]
