# Generated by Django 4.0.3 on 2022-04-04 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeRecommendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_url', models.URLField(unique=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='anime.animeinfomodel')),
            ],
            options={
                'verbose_name': 'Anime Recommendations',
            },
        ),
    ]
