# Generated by Django 4.0.3 on 2022-04-04 06:21

import apps.animecore.anime_characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCharacterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('character_image', models.ImageField(blank=True, default=None, null=True, upload_to=apps.animecore.anime_characters.models.FileField.anime_charater)),
            ],
            options={
                'verbose_name': 'Anime Characters',
            },
        ),
    ]
