# Generated by Django 4.0.3 on 2022-04-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_episodecommentmodel_and_more'),
        ('episode_comment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EpisodeCommentModel',
        ),
    ]
