# Generated by Django 4.0.3 on 2022-04-04 06:21

import apps.animecore.anime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime_genres', '0001_initial'),
        ('episode', '0001_initial'),
        ('anime_producers', '0001_initial'),
        ('anime_characters', '0001_initial'),
        ('anime_studios', '0001_initial'),
        ('anime_themes', '0001_initial'),
        ('anime_synonyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('anime_name', models.CharField(db_index=True, max_length=1024)),
                ('anime_name_japanese', models.CharField(db_index=True, max_length=1024, null=True)),
                ('anime_source', models.CharField(blank=True, max_length=128, null=True)),
                ('anime_aired_from', models.DateTimeField(blank=True, null=True)),
                ('anime_aired_to', models.DateTimeField(blank=True, null=True)),
                ('anime_cover', models.ImageField(blank=True, default=None, null=True, upload_to=apps.animecore.anime.models.FileField.anime_cover)),
                ('anime_synopsis', models.TextField(blank=True, null=True)),
                ('anime_background', models.TextField(blank=True, null=True)),
                ('anime_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('anime_characters', models.ManyToManyField(blank=True, to='anime_characters.animecharactermodel')),
                ('anime_episodes', models.ManyToManyField(blank=True, to='episode.episodemodel')),
                ('anime_genres', models.ManyToManyField(blank=True, to='anime_genres.animegenremodel')),
                ('anime_name_synonyms', models.ManyToManyField(blank=True, to='anime_synonyms.animesynonymmodel')),
                ('anime_producers', models.ManyToManyField(blank=True, to='anime_producers.animeproducermodel')),
                ('anime_studios', models.ManyToManyField(blank=True, to='anime_studios.animestudiomodel')),
                ('anime_themes', models.ManyToManyField(blank=True, to='anime_themes.animethememodel')),
            ],
            options={
                'verbose_name': 'Anime',
            },
        ),
    ]
