# Generated by Django 4.0.3 on 2022-04-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeGenreModel',
            fields=[
                ('mal_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Anime Genre',
            },
        ),
        migrations.AlterField(
            model_name='animeinfomodel',
            name='anime_genres',
            field=models.ManyToManyField(blank=True, to='anime.animegenremodel'),
        ),
    ]
