# Generated by Django 4.0.3 on 2022-04-04 07:33

import apps.animecore.anime_characters.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_animegenremodel_alter_animeinfomodel_anime_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCharacterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('character_image', models.ImageField(blank=True, default=None, null=True, upload_to=apps.animecore.anime_characters.models.FileField.anime_charater)),
            ],
            options={
                'verbose_name': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='AnimeProducerModel',
            fields=[
                ('mal_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Producer',
            },
        ),
        migrations.CreateModel(
            name='AnimeStudioModel',
            fields=[
                ('mal_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=50, unique=True)),
                ('type', models.CharField(db_index=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Studio',
            },
        ),
        migrations.CreateModel(
            name='AnimeSynonymModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Synonym',
            },
        ),
        migrations.CreateModel(
            name='AnimeThemeModel',
            fields=[
                ('mal_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=50, unique=True)),
                ('type', models.CharField(db_index=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Anime Theme',
            },
        ),
        migrations.AlterModelOptions(
            name='animegenremodel',
            options={'verbose_name': 'Genre'},
        ),
        migrations.CreateModel(
            name='AnimeRecommendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_url', models.URLField(unique=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='anime.animeinfomodel')),
            ],
            options={
                'verbose_name': 'Recommendations',
            },
        ),
        migrations.AlterField(
            model_name='animeinfomodel',
            name='anime_characters',
            field=models.ManyToManyField(blank=True, to='anime.animecharactermodel'),
        ),
        migrations.AlterField(
            model_name='animeinfomodel',
            name='anime_name_synonyms',
            field=models.ManyToManyField(blank=True, to='anime.animesynonymmodel'),
        ),
        migrations.AlterField(
            model_name='animeinfomodel',
            name='anime_producers',
            field=models.ManyToManyField(blank=True, to='anime.animeproducermodel'),
        ),
        migrations.AlterField(
            model_name='animeinfomodel',
            name='anime_studios',
            field=models.ManyToManyField(blank=True, to='anime.animestudiomodel'),
        ),
        migrations.AlterField(
            model_name='animeinfomodel',
            name='anime_themes',
            field=models.ManyToManyField(blank=True, to='anime.animethememodel'),
        ),
    ]
