# Generated by Django 4.0.3 on 2022-04-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_animecharactermodel_animeproducermodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animecharactermodel',
            options={'verbose_name': 'Character'},
        ),
        migrations.AlterModelOptions(
            name='animerecommendationmodel',
            options={'verbose_name': 'Recommendation'},
        ),
        migrations.AlterModelOptions(
            name='animethememodel',
            options={'verbose_name': 'Theme'},
        ),
    ]
