# Generated by Django 4.0.3 on 2022-04-04 06:21

import apps.animecore.episode.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episode_comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.BigIntegerField(default=0)),
                ('episode_name', models.CharField(db_index=True, max_length=1024)),
                ('episode_cover', models.ImageField(blank=True, default=None, null=True, upload_to=apps.animecore.episode.models.FileField.episode_cover)),
                ('episode_file', models.FileField(blank=True, default=None, null=True, upload_to=apps.animecore.episode.models.FileField.episode_upload)),
                ('episode_summary', models.TextField(blank=True, default='', null=True)),
                ('episode_comments', models.ManyToManyField(blank=True, to='episode_comment.episodecommentmodel')),
            ],
            options={
                'verbose_name': 'Episode',
            },
        ),
    ]
