# Generated by Django 4.0.3 on 2022-04-04 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('episode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_added', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='episode_comments',
            field=models.ManyToManyField(blank=True, to='episode.episodecommentmodel'),
        ),
    ]
